{"status": "failed", "name": "Fail when adding a new label predicate on a node that is already bound 1", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "LabelsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486033035, "historyId": "6618302a3594861b99ef992dcab09019", "start": 1578486032827, "steps": [{"status": "passed", "start": 1578486032829, "stop": 1578486033030, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486033031, "stop": 1578486033034, "name": "When executing query", "attachments": [{"source": "f5c56fce-34ff-4f15-8d83-7fd181ddeb07-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486033034, "stop": 1578486033035, "name": "Then a SyntaxError should be raised at compile time: VariableAlreadyBound", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 122, in step_impl\n    assert exception != None\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 122, in step_impl\n    assert exception != None\n"}, "uuid": "75d11d5c-70c0-4811-a6e1-79bdb93d88ef"}