{"status": "broken", "name": "Creating nodes from an unwound parameter list", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "crash"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "UnwindAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486174371, "historyId": "2eaa616d446abe61c9bfbc91d27333bd", "start": 1578486174086, "steps": [{"status": "passed", "start": 1578486174087, "stop": 1578486174291, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486174291, "stop": 1578486174292, "name": "And having executed", "attachments": [{"source": "b5e0371d-525b-43b7-bd92-041b1bd52d73-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486174292, "stop": 1578486174293, "name": "And parameters are", "attachments": [{"source": "dffdc0a3-5a7f-4e54-a977-ed812e6eac2c-attachment.csv", "type": "text/csv", "name": ".table"}]}, {"status": "passed", "start": 1578486174293, "stop": 1578486174370, "name": "When executing query", "attachments": [{"source": "1e6fb977-d360-4204-b586-7c5d11955cdf-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "c2252255-cf79-4bfe-9426-784b91599901-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486174371, "start": 1578486174370, "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 92, in step_impl\n    raise exception\n"}, "name": "Then the result should be, in order"}, {"status": "skipped", "start": 1578486174371, "stop": 1578486174371, "name": "And the side effects should be", "attachments": [{"source": "216031a0-a514-4416-bb03-d77cca12c6af-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 92, in step_impl\n    raise exception\n"}, "uuid": "a0545a2b-850b-4edc-901c-3a47ca1a29e8"}