{"status": "broken", "name": "Aggregation with named paths", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "crash"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MatchAcceptance2"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486061452, "historyId": "d0a406ccd832526f084d0a5623b01d94", "start": 1578486061135, "steps": [{"status": "passed", "start": 1578486061137, "stop": 1578486061345, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486061346, "stop": 1578486061350, "name": "And having executed", "attachments": [{"source": "dd44f162-bebf-4b48-9803-aa33dc48c985-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486061350, "stop": 1578486061451, "name": "When executing query", "attachments": [{"source": "3f3d13ee-e2c6-4fd2-ae8b-d375462986b9-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "8c77e6f4-d696-4ff7-b46d-f7e3dbd91ac1-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486061452, "start": 1578486061451, "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486061452, "stop": 1578486061452, "name": "And no side effects"}], "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "1957ba5c-0145-4560-b02e-ac9aaa7d6aad"}