{"status": "failed", "name": "`percentileCont()` failing on bad arguments -- @1.2 ", "parameters": [{"name": "percentile", "value": "-1"}], "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "FunctionsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486024633, "historyId": "ecf0adbc1ffeb9f92c65626b30ee8fce", "start": 1578486024407, "steps": [{"status": "passed", "start": 1578486024409, "stop": 1578486024623, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486024624, "stop": 1578486024627, "name": "And having executed", "attachments": [{"source": "cc7782ad-0c0e-4ce5-a567-31a4ca51a1e9-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486024627, "stop": 1578486024628, "name": "And parameters are", "attachments": [{"source": "bd94e79e-1f1d-4d1a-9b4a-54a1837d27f3-attachment.csv", "type": "text/csv", "name": ".table"}]}, {"status": "passed", "start": 1578486024628, "stop": 1578486024631, "name": "When executing query", "attachments": [{"source": "7194ab94-8c19-4800-81df-8bd490d9b8ca-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486024631, "stop": 1578486024632, "name": "Then a ArgumentError should be raised at runtime: NumberOutOfRange", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 107, in step_impl\n    assert \"ArgumentError\" in exception.message\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 107, in step_impl\n    assert \"ArgumentError\" in exception.message\n"}, "uuid": "48677983-56dd-421e-81a9-d8f5c9640437"}