{"status": "failed", "name": "Fail when adding new label predicate on a node that is already bound 5", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "LabelsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486033709, "historyId": "1b89743de242c7fdbefc3bd3d70e0774", "start": 1578486033488, "steps": [{"status": "passed", "start": 1578486033489, "stop": 1578486033703, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486033704, "stop": 1578486033707, "name": "When executing query", "attachments": [{"source": "c0b3b82d-e1bc-49b0-a265-ef8cd58adfb6-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486033708, "stop": 1578486033709, "name": "Then a SyntaxError should be raised at compile time: VariableAlreadyBound", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 122, in step_impl\n    assert exception != None\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 122, in step_impl\n    assert exception != None\n"}, "uuid": "617f9c3b-17d0-423f-83a3-07297be1fe37"}