{"status": "broken", "name": "Direction of traversed relationship is not significant for path equality, simple", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "crash"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "PathEquality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486114917, "historyId": "fff0d8bc3d42ef655c1a24fae8e538c4", "start": 1578486114682, "steps": [{"status": "passed", "start": 1578486114682, "stop": 1578486114792, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486114793, "stop": 1578486114796, "name": "And having executed", "attachments": [{"source": "883de656-ac68-4aca-a16f-d320e4900e22-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486114796, "stop": 1578486114916, "name": "When executing query", "attachments": [{"source": "573e5d29-4e14-4228-a567-a4a4a4bf58f6-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "87f867c7-9d26-413f-b4b4-424166b47231-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486114916, "start": 1578486114916, "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486114917, "stop": 1578486114917, "name": "And no side effects"}], "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "ebda2926-b439-4e10-984b-a27ef4ffb9c9"}